spring:
  application:
    name: task-manager-api
  datasource:
    url: jdbc:mysql://user-managment.cfu24gag8t8g.us-east-2.rds.amazonaws.com:3306/taskdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Shrihari1955

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
